import type { BoardSnapshot } from "./board-data";

export const demoSnapshots: BoardSnapshot[] = [
  {
    rows: [
      {
        id: "soccer",
        date: "MAR 28",
        name: "KAI SOCCER AT RIVER PARK",
        start: "09:30",
        end: "11:00",
        status: "STARTING SOON",
        statusTone: "yellow",
        tone: "blue",
      },
      {
        id: "market",
        date: "MAR 28",
        name: "FARMERS MARKET DOWNTOWN",
        start: "11:30",
        end: "12:15",
        status: "",
        tone: "yellow",
      },
      {
        id: "brunch",
        date: "MAR 28",
        name: "BRUNCH WITH ANA AT LINDEN",
        start: "12:30",
        end: "02:00",
        status: "",
        tone: "pink",
      },
      {
        id: "library",
        date: "MAR 28",
        name: "LIBRARY RUN EAST SIDE",
        start: "02:30",
        end: "03:15",
        status: "",
        tone: "green",
      },
      {
        id: "dinner",
        date: "MAR 28",
        name: "DINNER PREP AT HOME",
        start: "05:30",
        end: "06:20",
        status: "",
        tone: "yellow",
      },
      {
        id: "movie",
        date: "MAR 28",
        name: "MOVIE NIGHT IN LIVING ROOM",
        start: "07:30",
        end: "09:00",
        status: "",
        tone: "pink",
      },
      {
        id: "airport",
        date: "MAR 29",
        name: "AIRPORT RUN TERMINAL B",
        start: "08:00",
        end: "09:10",
        status: "",
        tone: "blue",
      },
    ],
  },
  {
    rows: [
      {
        id: "soccer",
        date: "MAR 28",
        name: "KAI SOCCER AT RIVER PARK",
        start: "09:30",
        end: "11:00",
        status: "IN PROGRESS",
        statusTone: "green",
        tone: "blue",
      },
      {
        id: "market",
        date: "MAR 28",
        name: "FARMERS MARKET DOWNTOWN",
        start: "11:30",
        end: "12:15",
        status: "STARTING SOON",
        statusTone: "yellow",
        tone: "yellow",
      },
      {
        id: "brunch",
        date: "MAR 28",
        name: "BRUNCH WITH ANA AT LINDEN",
        start: "12:30",
        end: "02:00",
        status: "",
        tone: "pink",
      },
      {
        id: "library",
        date: "MAR 28",
        name: "LIBRARY RUN EAST SIDE",
        start: "02:30",
        end: "03:15",
        status: "",
        tone: "green",
      },
      {
        id: "dinner",
        date: "MAR 28",
        name: "DINNER PREP AT HOME",
        start: "05:30",
        end: "06:20",
        status: "",
        tone: "yellow",
      },
      {
        id: "movie",
        date: "MAR 28",
        name: "MOVIE NIGHT IN LIVING ROOM",
        start: "07:30",
        end: "09:00",
        status: "",
        tone: "pink",
      },
      {
        id: "airport",
        date: "MAR 29",
        name: "AIRPORT RUN TERMINAL B",
        start: "08:00",
        end: "09:10",
        status: "",
        tone: "blue",
      },
    ],
  },
  {
    rows: [
      {
        id: "market",
        date: "MAR 28",
        name: "FARMERS MARKET DOWNTOWN",
        start: "11:30",
        end: "12:15",
        status: "IN PROGRESS",
        statusTone: "green",
        tone: "yellow",
      },
      {
        id: "brunch",
        date: "MAR 28",
        name: "BRUNCH WITH ANA AT LINDEN",
        start: "12:30",
        end: "02:00",
        status: "STARTING SOON",
        statusTone: "yellow",
        tone: "pink",
      },
      {
        id: "library",
        date: "MAR 28",
        name: "LIBRARY RUN EAST SIDE",
        start: "02:30",
        end: "03:15",
        status: "",
        tone: "green",
      },
      {
        id: "dinner",
        date: "MAR 28",
        name: "DINNER PREP AT HOME",
        start: "05:30",
        end: "06:20",
        status: "",
        tone: "yellow",
      },
      {
        id: "movie",
        date: "MAR 28",
        name: "MOVIE NIGHT IN LIVING ROOM",
        start: "07:30",
        end: "09:00",
        status: "",
        tone: "pink",
      },
      {
        id: "airport",
        date: "MAR 29",
        name: "AIRPORT RUN TERMINAL B",
        start: "08:00",
        end: "09:10",
        status: "",
        tone: "blue",
      },
      {
        id: "museum",
        date: "MAR 29",
        name: "MUSEUM DAY WITH KIDS",
        start: "10:30",
        end: "12:00",
        status: "",
        tone: "yellow",
      },
    ],
  },
];
